# Generated by Django 4.0.8 on 2023-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_field',
            field=models.URLField(default=11),
            preserve_default=False,
        ),
    ]
