# Generated by Django 4.0.8 on 2023-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_course_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='url_field',
            field=models.TextField(default=''),
        ),
    ]
